services:
  frontend:
    build: ./tricol-frontend
    ports:
      - "80:80"
    environment:
      - API_URL=http://backend:8080/api
    depends_on:
      - backend
    networks:
      - tricol-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gestionstock
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mypassword
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - tricol-network

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=gestionstock
      - MYSQL_ROOT_PASSWORD=mypassword
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmypassword"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - tricol-network

volumes:
  mysql-data:

networks:
  tricol-network:
    driver: bridge
