sonar.projectKey=gestion-stock-tricol
sonar.projectName=Gestion Stock Tricol
sonar.projectVersion=1.0.0

sonar.sources=gestion-stock/src/main/java
sonar.tests=gestion-stock/src/test/java
sonar.java.binaries=gestion-stock/target/classes
sonar.java.test.binaries=gestion-stock/target/test-classes

sonar.coverage.jacoco.xmlReportPaths=gestion-stock/target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=gestion-stock/target/surefire-reports

sonar.java.source=11
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/entity/**,**/dto/**,**/config/**,**/GestionStockApplication.java,**/ServletInitializer.java
